// config.bin - 17:08:20 08/09/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled
#include "COM_LIST_DEFINE.hpp"
#include "COM_LIST.hpp"
class CfgPatches {
	class motion_system {
		units[] = {"motion_system"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {};
	};
};
